version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - mlflow_data:/app/mlruns  # Maps to the same location as MLflow
      - ./backend/logs:/app/logs
    env_file:
      - ./backend/.env
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000  # Connect to MLflow service
    networks:
      - app-network
    depends_on:
      mlflow:
        condition: service_healthy
    restart: unless-stopped

  mlflow:
    image: python:3.11-slim
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlflow/mlruns  # Changed to match backend mapping
      - ./backend/logs:/mlflow/logs
    working_dir: /mlflow
    command: >
      sh -c "
        apt-get update && apt-get install -y curl &&
        pip install mlflow==2.8.1 &&
        mkdir -p /mlflow/mlruns /mlflow/logs &&
        exec mlflow server --backend-store-uri file:///mlflow/mlruns --default-artifact-root file:///mlflow/mlruns --host 0.0.0.0 --port 5000
      "
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 20s
      timeout: 10s
      retries: 15
      start_period: 120s

volumes:
  mlflow_data:
    driver: local

networks:
  app-network:
    driver: bridge